### ISSUE TITLE
Buggy checking

### ISSUE THREAD

**Issue by guiguan** [mhzed/find-free-port#4]
When I bind a port, for example 7001, to `0.0.0.0`, `find-free-port` returns unavailable for `0.0.0.0:7001` but available for `localhost:7001` :S

https://github.com/baalexander/node-portscanner works better

**Comment by mhzed** [comment]
Nodejs server.listen allows it, see https://nodejs.org/api/net.html#net_server_listen
Document and tests are updated to reflect this.
